name: Go CI

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  goci:
    name: goci
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
    permissions:
      actions: read
      contents: read
      packages: read
      statuses: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: .cache/go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.54
